version: "2.4"

networks:
  efb:
    name: efb

services:
  bot:
    container_name: efb-master
    image: eastonman/efb-docker
    restart: unless-stopped
    volumes:
      - ./profiles:/root/.ehforwarderbot/profiles
    networks:
      efb:
        aliases:
          - bot
    depends_on:
      - mirai

  mirai:
    container_name: efb-slave-qq-mirai
    image: eastonman/mirai-docker:latest
    restart: unless-stopped
    volumes: 
      - ./mirai-qq.yml:/config/MiraiApiHttp/setting.yml
    networks:
      efb:
        aliases:
          - mirai
    environment:
      - MIRAI_QQ_ACCOUNT=
      - MIRAI_QQ_PASSWORD=


